### ISSUE TITLE
设置当天时间段有问题

### ISSUE THREAD

**Issue by yzcheng90** [liuwan1992/CustomDatePicker#2]
博主好，这个控件设置当天时间段有问题
        customDatePicker1 = new CustomDatePicker(this, new CustomDatePicker.ResultHandler() {
            @Override
            public void handle(String time) { // 回调接口，获得选中的时间
                currentDate.setText(time.split(" ")[0]);
            }
        }, "2018-01-01 00:00", “2018-01-01 23:59”); // 初始化日期格式请用：yyyy-MM-dd HH:mm，否则不能正常运行
        customDatePicker1.showSpecificTime(false); // 不显示时和分
        customDatePicker1.setIsLoop(false); // 不允许循环滚动

这样设置"2018-01-01 00:00"到“2018-01-01 23:59”  导致前面的都能选

**Comment by liuwan1992** [comment]
已修复
