### ISSUE TITLE
时间范围显示控制

### ISSUE THREAD

**Issue by WiseDiligent** [liuwan1992/CustomDatePicker#6]
开始时间设置1900-01-01 结束时间选择当日时间，为什么时间弹窗就不出来了呢

**Comment by WiseDiligent** [comment]
现在发现设置开始时间在1970-02-01  ，要是在设置1970-01-01 就不显示了

**Comment by corlewang** [comment]
CustomDatePicker类构造方法里面去掉 beginTimestamp <= 0  这个判断即可显示

**Comment by liuwan1992** [comment]
时间戳是一个int值（-2147483648－2147483647），从0开始对应的是1970年01月01日00时00分00秒，在这个时间之前的时间戳是负数。我在代码里面屏蔽了负值时间戳，所以点击没有反应，有需要的话你可以去掉这个限制。
