### ISSUE TITLE
mScrollUnits 作用

### ISSUE THREAD

**Issue by mirse** [liuwan1992/CustomDatePicker#9]
你好，想咨询下
` (mScrollUnits & SCROLL_UNIT_HOUR) == SCROLL_UNIT_HOUR 与 (mScrollUnits & SCROLL_UNIT_MINUTE) == SCROLL_UNIT_MINUTE` 
的作用，谢谢

**Comment by liuwan1992** [comment]
通过二进制与运算来确定当前是否有展示“时”和“分”
